//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string Productname { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string Productname2 { get; set; }
        public Nullable<int> Qty2 { get; set; }
        public Nullable<double> UnitPrice2 { get; set; }
        public string Productname3 { get; set; }
        public Nullable<int> Qty3 { get; set; }
        public Nullable<double> UnitPrice3 { get; set; }
        public string Productname4 { get; set; }
        public Nullable<int> Qty4 { get; set; }
        public Nullable<double> UnitPrice4 { get; set; }
        public string Productname5 { get; set; }
        public Nullable<int> Qty5 { get; set; }
        public Nullable<double> UnitPrice5 { get; set; }
        public string Productname6 { get; set; }
        public Nullable<int> Qty6 { get; set; }
        public Nullable<double> UnitPrice6 { get; set; }
    }
}
